version: '3.8'

services:
  # Serviço de desenvolvimento
  nuuvify-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BUILDPLATFORM: linux/amd64
        PYTHON_VERSION: 3.12
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      - DEBUG=true
      - API_PREFIX=/api/v1
    restart: unless-stopped
    networks:
      - nuuvify-network

  # Serviço de produção
  nuuvify-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDPLATFORM: linux/amd64
        PYTHON_VERSION: 3.12
      target: production
    ports:
      - "8080:8000"
    environment:
      - DEBUG=false
      - API_PREFIX=/api/v1
    restart: unless-stopped
    networks:
      - nuuvify-network
    profiles:
      - production

  # Nginx reverse proxy (opcional para produção)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuuvify-prod
    networks:
      - nuuvify-network
    profiles:
      - production
      - nginx

networks:
  nuuvify-network:
    driver: bridge

volumes:
  app-data:
